### ISSUE TITLE
Not an issue, really, more of a question

### ISSUE THREAD

**Issue by ORYG1N** [715209/BRB-twitch-clips#1]
Hey, on the twitch BRB clips code, how would I go about removing the top ten clips and having it only play random clips from the past 30 days? If you don't mind, you can contact me on twitter.com/ORYG1N or Discord ORYG1N#6969

Thanks.

**Comment by 715209** [comment]
Hey @ORYG1N ,

Remove the first getClipsRequest. Then change the date to 30 instead of 7.
https://github.com/715209/BRB-twitch-clips/blob/9873827923e2b3c5c4b7595cfb0e4cdc16c07c3a/clips.html#L55-L64

You can also change this to include more clips.
https://github.com/715209/BRB-twitch-clips/blob/9873827923e2b3c5c4b7595cfb0e4cdc16c07c3a/clips.html#L128-L134

**Comment by ORYG1N** [comment]
So, just remove this line? 
**await this.getClipsRequest();**

Sorry, I'm very new to coding and haven't even worked with HTML in years.

EDIT: I think that does what I want. This stuff is really cool, thanks for posting it. One more thing, is it possible to have the "Clipped by: USER" text at the top of the clip or something similar?

**Comment by 715209** [comment]
Yes and change the 7 to 30.
https://github.com/715209/BRB-twitch-clips/blob/9873827923e2b3c5c4b7595cfb0e4cdc16c07c3a/clips.html#L57

I've added you on discord.

**Comment by maeglutz** [comment]
hi! i wanted to do exactly this, i've edited the code just like you said here, but it's still playing my older, most popular clips. any way you could help me out?
